version: '3.8'

services:
  xaosao-chat-frontend-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: always
